-- ChunkForge Open Source Database Schema
-- This script initializes the database for first-time setup

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Metadata schemas table
CREATE TABLE IF NOT EXISTS metadata_schemas (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    description TEXT,
    document_fields JSONB DEFAULT '[]' NOT NULL,
    chunk_fields JSONB DEFAULT '[]' NOT NULL,
    chunk_enrichment_prompt TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Uploads table (documents/files)
CREATE TABLE IF NOT EXISTS uploads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size INTEGER NOT NULL,
    chunking_strategy TEXT NOT NULL,
    markdown TEXT,
    markdown_path TEXT,
    metadata JSONB DEFAULT '{}' NOT NULL,
    schema_id UUID REFERENCES metadata_schemas(id) ON DELETE SET NULL,
    custom_metadata JSONB DEFAULT '{}' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chunks table (chunked segments of documents)
CREATE TABLE IF NOT EXISTS chunks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    upload_id UUID NOT NULL REFERENCES uploads(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    markdown_content TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    start_offset INTEGER,
    end_offset INTEGER,
    has_overlap BOOLEAN DEFAULT FALSE,
    metadata JSONB DEFAULT '{}' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_uploads_schema_id ON uploads(schema_id);
CREATE INDEX IF NOT EXISTS idx_uploads_created_at ON uploads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chunks_upload_id ON chunks(upload_id);
CREATE INDEX IF NOT EXISTS idx_chunks_position ON chunks(upload_id, "position");
CREATE INDEX IF NOT EXISTS idx_chunks_offsets ON chunks(upload_id, start_offset, end_offset);

-- Insert default schemas for getting started
INSERT INTO metadata_schemas (id, name, description, document_fields, chunk_fields, chunk_enrichment_prompt)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'Default',
    'Standard metadata fields for documents and chunks. This schema includes the default fields used by ChunkForge.',
    '[{"id": "d0000000-0000-0000-0001-000000000001", "name": "title", "type": "string", "label": "Title", "required": false, "description": "Document title", "autoGenerated": false}, {"id": "d0000000-0000-0000-0001-000000000002", "name": "author", "type": "string", "label": "Author", "required": false, "description": "Document author", "autoGenerated": false}, {"id": "d0000000-0000-0000-0001-000000000003", "name": "description", "type": "string", "label": "Description", "required": false, "description": "Document description or summary", "autoGenerated": false}]'::jsonb,
    '[{"id": "c0000000-0000-0000-0001-000000000001", "name": "title", "type": "string", "label": "Title", "required": false, "description": "Chunk title", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000002", "name": "author", "type": "string", "label": "Author", "required": false, "description": "Chunk author (overrides document author)", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000003", "name": "page", "type": "numeric", "label": "Page", "required": false, "validation": {"min": 1, "integer": true}, "description": "Page number reference", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000004", "name": "tags", "type": "array", "label": "Tags", "required": false, "description": "Categorization tags for this chunk", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000005", "name": "keywords", "type": "array", "label": "Keywords", "required": false, "description": "Search keywords for this chunk", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000006", "name": "summary", "type": "string", "label": "Summary", "required": false, "description": "Brief summary of the chunk content", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000007", "name": "heading_1", "type": "string", "label": "Heading 1", "required": false, "description": "H1 heading text above/containing this chunk", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-000000000008", "name": "heading_2", "type": "string", "label": "Heading 2", "required": false, "description": "H2 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-000000000009", "name": "heading_3", "type": "string", "label": "Heading 3", "required": false, "description": "H3 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000a", "name": "heading_4", "type": "string", "label": "Heading 4", "required": false, "description": "H4 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000b", "name": "heading_5", "type": "string", "label": "Heading 5", "required": false, "description": "H5 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000c", "name": "heading_6", "type": "string", "label": "Heading 6", "required": false, "description": "H6 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000d", "name": "section_path", "type": "string", "label": "Section Path", "required": false, "description": "Full hierarchical path (e.g., Chapter 1 > Section 1.1)", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000e", "name": "heading_level", "type": "numeric", "label": "Heading Level", "required": false, "validation": {"max": 6, "min": 1, "integer": true}, "description": "The heading level (1-6) that starts this chunk", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000f", "name": "token_count", "type": "numeric", "label": "Token Count", "required": false, "validation": {"min": 0, "integer": true}, "description": "Number of tokens in this chunk", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-000000000010", "name": "position_in_document", "type": "numeric", "label": "Position", "required": false, "validation": {"min": 0, "integer": true}, "description": "Zero-indexed position in chunk array", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-000000000011", "name": "total_chunks", "type": "numeric", "label": "Total Chunks", "required": false, "validation": {"min": 1, "integer": true}, "description": "Total number of chunks in document", "autoGenerated": true}]'::jsonb,
    NULL
) ON CONFLICT (id) DO NOTHING;

INSERT INTO metadata_schemas (id, name, description, document_fields, chunk_fields, chunk_enrichment_prompt)
VALUES (
    '00000000-0000-0000-0000-000000000002',
    'Extension Guides',
    'Schema for agricultural extension guides with pest and pesticide extraction.',
    '[{"id": "d0000000-0000-0000-0001-000000000001", "name": "title", "type": "string", "label": "Title", "required": false, "description": "Document title", "autoGenerated": false}, {"id": "d0000000-0000-0000-0001-000000000002", "name": "author", "type": "string", "label": "Author", "required": false, "description": "Document author", "autoGenerated": false}, {"id": "d0000000-0000-0000-0001-000000000003", "name": "description", "type": "string", "label": "Description", "required": false, "description": "Document description or summary", "autoGenerated": false}]'::jsonb,
    '[{"id": "c0000000-0000-0000-0001-000000000003", "name": "page", "type": "numeric", "label": "Page", "required": false, "validation": {"min": 1, "integer": true}, "description": "Page number reference", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000004", "name": "tags", "type": "array", "label": "Tags", "required": false, "description": "Categorization tags for this chunk", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000005", "name": "keywords", "type": "array", "label": "Keywords", "required": false, "description": "Search keywords for this chunk", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000006", "name": "summary", "type": "string", "label": "Summary", "required": false, "description": "Brief summary of the chunk content", "autoGenerated": false}, {"id": "c0000000-0000-0000-0001-000000000007", "name": "heading_1", "type": "string", "label": "Heading 1", "required": false, "description": "H1 heading text above/containing this chunk", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-000000000008", "name": "heading_2", "type": "string", "label": "Heading 2", "required": false, "description": "H2 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-000000000009", "name": "heading_3", "type": "string", "label": "Heading 3", "required": false, "description": "H3 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000a", "name": "heading_4", "type": "string", "label": "Heading 4", "required": false, "description": "H4 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000b", "name": "heading_5", "type": "string", "label": "Heading 5", "required": false, "description": "H5 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000c", "name": "heading_6", "type": "string", "label": "Heading 6", "required": false, "description": "H6 heading text", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000d", "name": "section_path", "type": "string", "label": "Section Path", "required": false, "description": "Full hierarchical path (e.g., Chapter 1 > Section 1.1)", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000e", "name": "heading_level", "type": "numeric", "label": "Heading Level", "required": false, "validation": {"max": 6, "min": 1, "integer": true}, "description": "The heading level (1-6) that starts this chunk", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-00000000000f", "name": "token_count", "type": "numeric", "label": "Token Count", "required": false, "validation": {"min": 0, "integer": true}, "description": "Number of tokens in this chunk", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-000000000010", "name": "position_in_document", "type": "numeric", "label": "Position", "required": false, "validation": {"min": 0, "integer": true}, "description": "Zero-indexed position in chunk array", "autoGenerated": true}, {"id": "c0000000-0000-0000-0001-000000000011", "name": "total_chunks", "type": "numeric", "label": "Total Chunks", "required": false, "validation": {"min": 1, "integer": true}, "description": "Total number of chunks in document", "autoGenerated": true}, {"id": "7b64a249-2352-4ce9-96b9-2a4fc706d432", "name": "pest", "type": "array", "label": "Pest", "required": false, "validation": {}, "description": "What type of pest or pests is this chunk related to.", "autoGenerated": false}, {"id": "0b56c699-3c22-46e6-bb8f-0f2eb4bec103", "name": "pesticides", "type": "json", "label": "Pesticides", "required": false, "description": "What pesticides are mentioned and their rates.", "autoGenerated": false}]'::jsonb,
    'For each chunk extract the pest or pests that are mentioned for the {{pest}} array and then extract any pesticide products mentioned for the {{pesticides}} array. Also extract {{tags}} and {{keywords}} that would assist in retrieval. Provide a succinct {{summary}} for each section.'
) ON CONFLICT (id) DO NOTHING;
