import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { SchemaSelector } from '@/components/SchemaSelector';
import { SchemaEditorDialog } from '@/components/SchemaEditorDialog';
import { DynamicField } from '@/components/DynamicField';
import { ChunkMetadata, DocumentMetadata } from '@shared/schema';
import { MetadataSchema } from '@shared/metadata-schema';
import { FileText, Layers, Settings, Sparkles } from 'lucide-react';
import { useEnrichChunk, useEnrichChunks, ENRICH_LIMIT_OPTIONS, parseEnrichLimit, type EnrichLimitValue } from '@/hooks/useChunkEnrichment';
import { useToast } from '@/hooks/use-toast';

interface MetadataPanelProps {
  // Upload ID (for enrichment API calls)
  uploadId: string;
  // Chunk metadata (for selected chunk)
  chunkMetadata: ChunkMetadata | null;
  onChunkMetadataChange: (metadata: ChunkMetadata) => void;
  selectedChunkId: string | null;
  // Document metadata
  documentMetadata: DocumentMetadata;
  onDocumentMetadataChange: (metadata: DocumentMetadata) => void;
  // Document title (separate from metadata for display in header)
  documentTitle: string;
  onDocumentTitleChange: (title: string) => void;
  // Schema support
  schema: MetadataSchema | null;
  onSchemaChange: (schemaId: string | null) => void;
}

export function MetadataPanel({
  uploadId,
  chunkMetadata,
  onChunkMetadataChange,
  selectedChunkId,
  documentMetadata,
  onDocumentMetadataChange,
  documentTitle,
  onDocumentTitleChange,
  schema,
  onSchemaChange,
}: MetadataPanelProps) {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState<string>('document');
  const [schemaEditorOpen, setSchemaEditorOpen] = useState(false);
  const [enrichLimit, setEnrichLimit] = useState<EnrichLimitValue>('3');

  // Enrichment mutations
  const enrichChunkMutation = useEnrichChunk();
  const enrichChunksMutation = useEnrichChunks();

  // Check if enrichment is available
  const canEnrich = schema?.chunkEnrichmentPrompt &&
    schema.chunkFields?.some(f => !f.autoGenerated);

  const handleEnrichChunk = () => {
    if (!selectedChunkId) return;

    enrichChunkMutation.mutate(
      { uploadId, chunkId: selectedChunkId },
      {
        onSuccess: (data) => {
          toast({
            title: 'Chunk Enriched',
            description: `Successfully extracted ${Object.keys(data.enrichedFields).length} fields`,
          });
        },
        onError: (error: any) => {
          toast({
            title: 'Enrichment Failed',
            description: error.message || 'Failed to enrich chunk metadata',
            variant: 'destructive',
          });
        },
      }
    );
  };

  const handleEnrichChunks = () => {
    const limit = parseEnrichLimit(enrichLimit);

    enrichChunksMutation.mutate(
      { uploadId, limit },
      {
        onSuccess: (data) => {
          toast({
            title: 'Chunks Enriched',
            description: `Enriched ${data.summary.enriched} of ${data.summary.processed} chunks${data.summary.failed > 0 ? ` (${data.summary.failed} failed)` : ''}`,
          });
        },
        onError: (error: any) => {
          toast({
            title: 'Enrichment Failed',
            description: error.message || 'Failed to enrich chunk metadata',
            variant: 'destructive',
          });
        },
      }
    );
  };

  return (
    <div className="w-80 border-l bg-card p-4 overflow-y-auto h-full">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-2 mb-4">
          <TabsTrigger value="document" className="flex items-center gap-1">
            <FileText className="h-4 w-4" />
            Document
          </TabsTrigger>
          <TabsTrigger value="chunk" className="flex items-center gap-1" disabled={!selectedChunkId}>
            <Layers className="h-4 w-4" />
            Chunk
          </TabsTrigger>
        </TabsList>

        {/* Document Metadata Tab */}
        <TabsContent value="document" className="mt-0">
          {/* Schema Selector */}
          <div className="mb-4 space-y-2">
            <div className="flex items-center justify-between">
              <Label className="text-sm">Metadata Schema</Label>
              <Button
                variant="ghost"
                size="sm"
                className="h-6 px-2"
                onClick={() => setSchemaEditorOpen(true)}
              >
                <Settings className="h-3 w-3 mr-1" />
                {schema ? 'Edit' : 'Create'}
              </Button>
            </div>
            <SchemaSelector
              value={schema?.id || null}
              onChange={onSchemaChange}
              onCreateNew={() => setSchemaEditorOpen(true)}
            />
          </div>

          {/* AI Enrichment Section */}
          {canEnrich && (
            <div className="mb-4 p-3 rounded-lg border bg-muted/30">
              <div className="flex items-center gap-2 mb-2">
                <Sparkles className="h-4 w-4 text-primary" />
                <span className="text-sm font-medium">AI Enrichment</span>
              </div>
              <div className="flex items-center gap-2">
                <Select value={enrichLimit} onValueChange={(v) => setEnrichLimit(v as EnrichLimitValue)}>
                  <SelectTrigger className="w-[130px] h-8 text-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {ENRICH_LIMIT_OPTIONS.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        {option.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-8 flex-1"
                  onClick={handleEnrichChunks}
                  disabled={enrichChunksMutation.isPending}
                >
                  <Sparkles className="h-3 w-3 mr-1" />
                  {enrichChunksMutation.isPending ? 'Enriching...' : 'Enrich'}
                </Button>
              </div>
            </div>
          )}

          {/* Document Title (always editable, not from schema) */}
          <div className="space-y-2 mb-4">
            <Label htmlFor="doc-title">Document Title</Label>
            <Input
              id="doc-title"
              value={documentTitle}
              onChange={(e) => onDocumentTitleChange(e.target.value)}
              placeholder="Enter document title..."
              data-testid="input-doc-title"
            />
          </div>

          {schema && schema.documentFields && schema.documentFields.length > 0 ? (
            <Accordion type="multiple" defaultValue={['doc-editable', 'doc-auto']} className="w-full">
              {/* User-Editable Fields (autoGenerated: false) */}
              {schema.documentFields.filter(f => !f.autoGenerated).length > 0 && (
                <AccordionItem value="doc-editable">
                  <AccordionTrigger>
                    Editable Fields
                    <Badge variant="secondary" className="ml-2 text-[10px]">
                      {schema.documentFields.filter(f => !f.autoGenerated).length}
                    </Badge>
                  </AccordionTrigger>
                  <AccordionContent className="space-y-4">
                    {schema.documentFields.filter(f => !f.autoGenerated).map((field) => (
                      <DynamicField
                        key={field.id}
                        field={field}
                        value={documentMetadata.custom?.[field.name] ?? (documentMetadata as any)[field.name]}
                        onChange={(value) => {
                          // Standard fields go at root level, others in custom
                          const standardFields = ['title', 'author', 'description', 'pageCount', 'fileSize', 'uploadedAt', 'originalFilename'];
                          if (standardFields.includes(field.name)) {
                            onDocumentMetadataChange({ ...documentMetadata, [field.name]: value });
                          } else {
                            onDocumentMetadataChange({
                              ...documentMetadata,
                              custom: { ...(documentMetadata.custom || {}), [field.name]: value },
                            });
                          }
                        }}
                      />
                    ))}
                  </AccordionContent>
                </AccordionItem>
              )}

              {/* Auto-Generated Fields (autoGenerated: true) - Read Only */}
              {schema.documentFields.filter(f => f.autoGenerated).length > 0 && (
                <AccordionItem value="doc-auto">
                  <AccordionTrigger>
                    Auto-Generated
                    <Badge variant="outline" className="ml-2 text-[10px]">
                      {schema.documentFields.filter(f => f.autoGenerated).length}
                    </Badge>
                  </AccordionTrigger>
                  <AccordionContent className="space-y-3">
                    {schema.documentFields.filter(f => f.autoGenerated).map((field) => {
                      const value = documentMetadata.custom?.[field.name] ?? (documentMetadata as any)[field.name];
                      let displayValue: string | number = 'N/A';

                      // Format specific fields
                      if (value === undefined || value === null) {
                        displayValue = 'N/A';
                      } else if (field.name === 'fileSize' && typeof value === 'number') {
                        displayValue = `${(value / 1024).toFixed(1)} KB`;
                      } else if (field.name === 'uploadedAt' && (typeof value === 'string' || typeof value === 'number')) {
                        displayValue = new Date(value).toLocaleDateString();
                      } else if (Array.isArray(value)) {
                        displayValue = value.join(', ') || 'None';
                      } else if (typeof value === 'object') {
                        displayValue = JSON.stringify(value);
                      } else {
                        displayValue = String(value);
                      }

                      return (
                        <div key={field.id} className="flex justify-between items-center py-1">
                          <span className="text-sm text-muted-foreground">{field.label}</span>
                          <span className="text-sm font-medium truncate max-w-[150px]" title={String(displayValue)}>
                            {displayValue}
                          </span>
                        </div>
                      );
                    })}
                  </AccordionContent>
                </AccordionItem>
              )}
            </Accordion>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              <p className="text-sm">No schema selected or schema has no document fields</p>
            </div>
          )}
        </TabsContent>

        {/* Chunk Metadata Tab */}
        <TabsContent value="chunk" className="mt-0">
          {!selectedChunkId ? (
            <div className="text-center py-8 text-muted-foreground">
              <Layers className="h-12 w-12 mx-auto mb-2 opacity-50" />
              <p>Select a chunk to edit its metadata</p>
            </div>
          ) : chunkMetadata && schema && schema.chunkFields ? (
            <>
              {/* Single Chunk Enrichment Button */}
              {canEnrich && (
                <div className="mb-4">
                  <Button
                    variant="outline"
                    size="sm"
                    className="w-full"
                    onClick={handleEnrichChunk}
                    disabled={enrichChunkMutation.isPending}
                  >
                    <Sparkles className="h-4 w-4 mr-2" />
                    {enrichChunkMutation.isPending ? 'Enriching...' : 'Enrich This Chunk with AI'}
                  </Button>
                </div>
              )}

              <Accordion type="multiple" defaultValue={['chunk-editable', 'chunk-auto']} className="w-full">
              {/* User-Editable Chunk Fields (autoGenerated: false) */}
              {schema.chunkFields.filter(f => !f.autoGenerated).length > 0 && (
                <AccordionItem value="chunk-editable">
                  <AccordionTrigger>
                    Editable Fields
                    <Badge variant="secondary" className="ml-2 text-[10px]">
                      {schema.chunkFields.filter(f => !f.autoGenerated).length}
                    </Badge>
                  </AccordionTrigger>
                  <AccordionContent className="space-y-4">
                    {schema.chunkFields.filter(f => !f.autoGenerated).map((field) => {
                      // Get value from chunk metadata
                      // For editable fields, prefer custom (where AI enrichment saves) over root level
                      // This ensures enriched values are displayed even if root has empty arrays
                      const rootValue = (chunkMetadata as any)[field.name];
                      const customValue = chunkMetadata.custom?.[field.name];
                      // Use custom if it has a value, otherwise fall back to root
                      const value = customValue !== undefined && customValue !== null
                        ? customValue
                        : rootValue;

                      return (
                        <DynamicField
                          key={field.id}
                          field={field}
                          value={value}
                          onChange={(newValue) => {
                            // All editable chunk fields save to custom for consistency with AI enrichment
                            onChunkMetadataChange({
                              ...chunkMetadata,
                              custom: { ...(chunkMetadata.custom || {}), [field.name]: newValue },
                            });
                          }}
                        />
                      );
                    })}
                  </AccordionContent>
                </AccordionItem>
              )}

              {/* Auto-Generated Chunk Fields (autoGenerated: true) - Read Only */}
              {schema.chunkFields.filter(f => f.autoGenerated).length > 0 && (
                <AccordionItem value="chunk-auto">
                  <AccordionTrigger>
                    Auto-Generated
                    <Badge variant="outline" className="ml-2 text-[10px]">
                      {schema.chunkFields.filter(f => f.autoGenerated).length}
                    </Badge>
                  </AccordionTrigger>
                  <AccordionContent className="space-y-3">
                    {schema.chunkFields.filter(f => f.autoGenerated).map((field) => {
                      // Get value from chunk metadata (check both root level and custom)
                      const value = (chunkMetadata as any)[field.name] ?? chunkMetadata.custom?.[field.name];
                      let displayValue = value;

                      // Format specific fields
                      if (field.name === 'heading_level' && value !== undefined) {
                        displayValue = `H${value}`;
                      } else if (field.type === 'array' && Array.isArray(value)) {
                        displayValue = value.join(', ') || 'None';
                      }

                      return (
                        <div key={field.id} className="flex justify-between items-center py-1">
                          <span className="text-sm text-muted-foreground">{field.label}</span>
                          {field.name === 'token_count' ? (
                            <Badge variant="secondary">{displayValue ?? 'N/A'}</Badge>
                          ) : field.name === 'heading_level' && value !== undefined ? (
                            <Badge variant="outline">{displayValue}</Badge>
                          ) : (
                            <span className="text-sm font-medium truncate max-w-[150px]" title={String(displayValue)}>
                              {displayValue ?? 'N/A'}
                            </span>
                          )}
                        </div>
                      );
                    })}
                  </AccordionContent>
                </AccordionItem>
              )}
            </Accordion>
            </>
          ) : chunkMetadata ? (
            <div className="text-center py-8 text-muted-foreground">
              <p className="text-sm">No schema selected or schema has no chunk fields</p>
            </div>
          ) : null}
        </TabsContent>
      </Tabs>

      {/* Schema Editor Dialog */}
      <SchemaEditorDialog
        open={schemaEditorOpen}
        onOpenChange={setSchemaEditorOpen}
        schema={schema}
        onSaved={(savedSchema) => {
          onSchemaChange(savedSchema.id);
        }}
      />
    </div>
  );
}
